---
auth:
  required: true
  queryParams:
  - name: Parameter name
    value: Parameter value
  headerParams:
  - name: Parameter name
    value: Parameter value
testConfiguration:
  testPaths:
  - testPath: Path 1
    operations:
    - operationId: Operation ID
      method: get
      testParameters:
      - name: Test parameter name
        weight: 0.5
        generator:
          type: Generator type
          genParameters:
          - name: Parameter name
            values:
            - Parameter value
            objectValues: null
          - name: Parameter name 2
            values:
            - Parameter value
            objectValues: null
      paramDependencies: null
      expectedResponse: Expected HTTP code
